/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Personaje;

import Cliente.Cliente;
import java.util.Arrays; 
import Cliente.Pantalla;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author jecheverria
 */
public class CrearPersonaje extends javax.swing.JFrame {
    Arma[] Armas;
    Cliente cliente;
    Personaje[] Personajes;
    Personaje[] PersonajesArchivo;
    Funciones f = new Funciones();
    int Contador = 0;
    boolean[] ArmasPersonaje;
    /**
     * Creates new form CrearPersonaje
     * 
     */
    public CrearPersonaje(Cliente client, Personaje[] personajes) {
        this.Armas =new Arma[5];
        this.cliente = client;
        read_personajes();
        this.ArmasPersonaje = new boolean[4] ;
        for (boolean ArmaCreada : ArmasPersonaje){
            ArmaCreada = false;
        }
        this.Personajes = personajes;
        initComponents();
        cmb_NombresPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(f.PersonajeArraytoStringArray(PersonajesArchivo)));
//        cmb_NombresPersonajes.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Personaje1 = new javax.swing.JPanel();
        txf_Arma2Personaje1 = new javax.swing.JTextField();
        txf_Arma3Personaje1 = new javax.swing.JTextField();
        txf_Arma4Personaje1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_StatsArma1Personaje1 = new javax.swing.JList<>();
        txf_Arma5Personaje1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_StatsArma2Personaje1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_StatsArma3Personaje1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_StatsArma4Personaje1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_StatsArma5Personaje1 = new javax.swing.JList<>();
        btn_VerEstadisticasPersonaje1 = new javax.swing.JButton();
        lbl_Armas = new javax.swing.JLabel();
        txf_Arma1Personaje1 = new javax.swing.JTextField();
        lbl_Apariencia1 = new javax.swing.JLabel();
        txf_Apariencia1 = new javax.swing.JTextField();
        lbl_DireccionApariencia1 = new javax.swing.JLabel();
        btn_VerPersonaje1 = new javax.swing.JButton();
        lbl_nombre1 = new javax.swing.JLabel();
        txf_Nombre1 = new javax.swing.JTextField();
        cmb_TipoPersonaje1 = new javax.swing.JComboBox<>();
        lbl_TipoPersonaje1 = new javax.swing.JLabel();
        lbl_ErrorArma1 = new javax.swing.JLabel();
        btn_Empezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_NombresPersonajes = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lst_personajes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Personaje1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        txf_Arma2Personaje1.setText("Espada del Olimpo");
        txf_Arma2Personaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Arma2Personaje1ActionPerformed(evt);
            }
        });

        txf_Arma3Personaje1.setText("Scout Rifle");

        txf_Arma4Personaje1.setText("Espadas del caos");

        lst_StatsArma1Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_StatsArma1Personaje1);

        txf_Arma5Personaje1.setText("Cangreburgers");

        lst_StatsArma2Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lst_StatsArma2Personaje1);

        lst_StatsArma3Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_StatsArma3Personaje1);

        lst_StatsArma4Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lst_StatsArma4Personaje1);

        lst_StatsArma5Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lst_StatsArma5Personaje1);

        btn_VerEstadisticasPersonaje1.setText("Generar Armas");
        btn_VerEstadisticasPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerEstadisticasPersonaje1ActionPerformed(evt);
            }
        });

        lbl_Armas.setText("Armas:");

        txf_Arma1Personaje1.setText("Espatula");
        txf_Arma1Personaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Arma1Personaje1ActionPerformed(evt);
            }
        });

        lbl_Apariencia1.setText("<Imagen apariencia>");

<<<<<<< HEAD
        txf_DireccionApariencia1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_DireccionApariencia1.setText("C:\\Users\\PC\\Pictures\\Apariencias\\Bob Esponja.png");
        txf_DireccionApariencia1.addActionListener(new java.awt.event.ActionListener() {
=======
        txf_Apariencia1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_Apariencia1.setText("C:\\Users\\jecheverria\\Apariencias\\BobEsponja.png");
        txf_Apariencia1.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> master
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Apariencia1ActionPerformed(evt);
            }
        });

        lbl_DireccionApariencia1.setText("Direccion de apariencia");

        btn_VerPersonaje1.setText("Ver");
        btn_VerPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerPersonaje1ActionPerformed(evt);
            }
        });

        lbl_nombre1.setText("Nombre de personaje:");

        txf_Nombre1.setText("Bob Esponja");

        cmb_TipoPersonaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego", "Aire", "Agua", "Magia Blanca", "Magia Negra", "Electricidad", "Hielo", "Acido ", "Espiritual ", "Hierro" }));
        cmb_TipoPersonaje1.setSelectedIndex(-1);
        cmb_TipoPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_TipoPersonaje1ActionPerformed(evt);
            }
        });

        lbl_TipoPersonaje1.setText("Tipo:");

        lbl_ErrorArma1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout pnl_Personaje1Layout = new javax.swing.GroupLayout(pnl_Personaje1);
        pnl_Personaje1.setLayout(pnl_Personaje1Layout);
        pnl_Personaje1Layout.setHorizontalGroup(
            pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txf_Nombre1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cmb_TipoPersonaje1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_TipoPersonaje1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma5Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(txf_Arma3Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txf_Arma1Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma4Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma2Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addComponent(lbl_Armas)
                                .addGap(7, 7, 7)
                                .addComponent(btn_VerEstadisticasPersonaje1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ErrorArma1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                .addComponent(lbl_DireccionApariencia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_VerPersonaje1))
                            .addComponent(txf_Apariencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Apariencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_Personaje1Layout.setVerticalGroup(
            pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre1)
                    .addComponent(lbl_TipoPersonaje1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_TipoPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DireccionApariencia1)
                    .addComponent(btn_VerPersonaje1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_Apariencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Apariencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_Armas)
                    .addComponent(btn_VerEstadisticasPersonaje1)
                    .addComponent(lbl_ErrorArma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma2Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma1Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma4Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma3Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_Arma5Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

<<<<<<< HEAD
        pnl_Personaje2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        lst_StatsArma1Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(lst_StatsArma1Personaje2);

        txf_Arma5Personaje2.setText("Revolver");

        lst_StatsArma2Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(lst_StatsArma2Personaje2);

        lst_StatsArma3Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(lst_StatsArma3Personaje2);

        btn_VerEstadisticasPersonaje2.setText("Generar Armas");
        btn_VerEstadisticasPersonaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerEstadisticasPersonaje2ActionPerformed(evt);
            }
        });

        lbl_Armas1.setText("Armas:");

        txf_Arma1Personaje2.setText("Mente");

        txf_Arma2Personaje2.setText("Dedos");

        txf_Arma3Personaje2.setText("Piedras");

        txf_Arma4Personaje2.setText("Pistola de portales");

        lst_StatsArma4Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(lst_StatsArma4Personaje2);

        lst_StatsArma5Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(lst_StatsArma5Personaje2);

        txf_DireccionApariencia2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_DireccionApariencia2.setText("C:\\Users\\PC\\Pictures\\Apariencias\\Calamardo.png");
        txf_DireccionApariencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_DireccionApariencia2ActionPerformed(evt);
            }
        });

        lbl_Apariencia2.setText("<Imagen apariencia>");

        lbl_DireccionApariencia2.setText("Direccion de apariencia");

        btn_VerPersonaje2.setText("Ver");
        btn_VerPersonaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerPersonaje2ActionPerformed(evt);
            }
        });

        lbl_nombre2.setText("Nombre de personaje:");

        txf_Nombre2.setText("Patricio");

        cmb_TipoPersonaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego", "Aire", "Agua", "Magia Blanca", "Magia Negra", "Electricidad", "Hielo", "Acido ", "Espiritual ", "Hierro" }));
        cmb_TipoPersonaje2.setSelectedIndex(-1);
        cmb_TipoPersonaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_TipoPersonaje2ActionPerformed(evt);
            }
        });

        lbl_TipoPersonaje2.setText("Tipo:");

        lbl_ErrorArma2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout pnl_Personaje2Layout = new javax.swing.GroupLayout(pnl_Personaje2);
        pnl_Personaje2.setLayout(pnl_Personaje2Layout);
        pnl_Personaje2Layout.setHorizontalGroup(
            pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txf_Nombre2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_TipoPersonaje2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                .addComponent(lbl_TipoPersonaje2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane8)
                                .addComponent(txf_Arma3Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_Arma4Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_Arma2Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Personaje2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_Arma5Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)))
                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                        .addComponent(lbl_DireccionApariencia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_VerPersonaje2))
                    .addComponent(txf_DireccionApariencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma1Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                        .addComponent(lbl_Armas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                .addComponent(btn_VerEstadisticasPersonaje2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ErrorArma2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Apariencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Personaje2Layout.setVerticalGroup(
            pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre2)
                    .addComponent(lbl_TipoPersonaje2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_TipoPersonaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DireccionApariencia2)
                    .addComponent(btn_VerPersonaje2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_DireccionApariencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Apariencia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_ErrorArma2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Armas1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_VerEstadisticasPersonaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma1Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma2Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma4Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma3Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_Arma5Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_Personaje3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        lbl_Armas2.setText("Armas:");

        txf_Arma1Personaje3.setText("Tentaculos");

        txf_Arma2Personaje3.setText("Clarinete");

        txf_Arma3Personaje3.setText("Nariz");

        txf_Arma4Personaje3.setText("MP5");

        lst_StatsArma4Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(lst_StatsArma4Personaje3);

        lst_StatsArma5Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(lst_StatsArma5Personaje3);

        btn_VerEstadisticasPersonaje3.setText("Generar Armas");
        btn_VerEstadisticasPersonaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerEstadisticasPersonaje3ActionPerformed(evt);
            }
        });

        lst_StatsArma1Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(lst_StatsArma1Personaje3);

        txf_Arma5Personaje3.setText("Mjolnir");
        txf_Arma5Personaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Arma5Personaje3ActionPerformed(evt);
            }
        });

        lst_StatsArma2Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(lst_StatsArma2Personaje3);

        lst_StatsArma3Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(lst_StatsArma3Personaje3);

        txf_DireccionApariencia3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_DireccionApariencia3.setText("C:\\Users\\PC\\Pictures\\Apariencias\\patricio.png");
        txf_DireccionApariencia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_DireccionApariencia3ActionPerformed(evt);
            }
        });

        lbl_Apariencia3.setText("<Imagen apariencia>");

        lbl_DireccionApariencia3.setText("Direccion de apariencia");

        btn_VerPersonaje3.setText("Ver");
        btn_VerPersonaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerPersonaje3ActionPerformed(evt);
            }
        });

        lbl_nombre3.setText("Nombre de personaje:");

        txf_Nombre3.setText("Calamardo");
        txf_Nombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Nombre3ActionPerformed(evt);
            }
        });

        cmb_TipoPersonaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego", "Aire", "Agua", "Magia Blanca", "Magia Negra", "Electricidad", "Hielo", "Acido ", "Espiritual ", "Hierro" }));
        cmb_TipoPersonaje3.setSelectedIndex(-1);
        cmb_TipoPersonaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_TipoPersonaje3ActionPerformed(evt);
            }
        });

        lbl_TipoPersonaje3.setText("Tipo:");

        lbl_ErrorArma6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        lbl_ErrorArma3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout pnl_Personaje3Layout = new javax.swing.GroupLayout(pnl_Personaje3);
        pnl_Personaje3.setLayout(pnl_Personaje3Layout);
        pnl_Personaje3Layout.setHorizontalGroup(
            pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txf_Nombre3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_TipoPersonaje3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                .addComponent(lbl_TipoPersonaje3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Arma5Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane13)
                                .addComponent(txf_Arma3Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txf_Arma1Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Arma4Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Arma2Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addComponent(lbl_DireccionApariencia3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_VerPersonaje3))
                    .addComponent(txf_DireccionApariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addComponent(lbl_Armas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Apariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                .addComponent(btn_VerEstadisticasPersonaje3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ErrorArma3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje3Layout.createSequentialGroup()
                    .addContainerGap(181, Short.MAX_VALUE)
                    .addComponent(lbl_ErrorArma6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        pnl_Personaje3Layout.setVerticalGroup(
            pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre3)
                            .addComponent(lbl_TipoPersonaje3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_TipoPersonaje3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_VerPersonaje3)
                    .addComponent(lbl_DireccionApariencia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_DireccionApariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Apariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Armas2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_VerEstadisticasPersonaje3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ErrorArma3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma2Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma1Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Arma4Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Arma3Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_Arma5Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addComponent(lbl_ErrorArma6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(255, 255, 255)))
        );

        pnl_Personaje4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));

        txf_Arma2Personaje4.setText("Monedas");
        txf_Arma2Personaje4.addActionListener(new java.awt.event.ActionListener() {
=======
        btn_Empezar.setText("Empezar");
        btn_Empezar.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> master
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpezarActionPerformed(evt);
            }
        });

        jLabel1.setText("Personajes Disponibles:");

        cmb_NombresPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_NombresPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_NombresPersonajesActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        txf_DireccionApariencia4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_DireccionApariencia4.setText("C:\\Users\\PC\\Pictures\\Apariencias\\Don Cangrejo.png");
        txf_DireccionApariencia4.addActionListener(new java.awt.event.ActionListener() {
=======
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> master
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(lst_personajes);

        jLabel2.setText("Escuadron:");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_eliminar)
                                    .addComponent(btn_agregar)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_NombresPersonajes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Empezar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)))
                .addComponent(pnl_Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_NombresPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregar)
                        .addGap(14, 14, 14)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Empezar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_Apariencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Apariencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Apariencia1ActionPerformed

    private void txf_Arma1Personaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Arma1Personaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Arma1Personaje4ActionPerformed

    private void btn_EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpezarActionPerformed
<<<<<<< HEAD
        boolean errores = false;
        String errors = "";
        if (txf_Nombre1.getText().length()!=0 & txf_Nombre2.getText().length()!=0 & txf_Nombre3.getText().length()!=0 & txf_Nombre4.getText().length()!=0){
            Personajes[0].setNombre(txf_Nombre1.getText());
            Personajes[1].setNombre(txf_Nombre2.getText());
            Personajes[2].setNombre(txf_Nombre3.getText());
            Personajes[3].setNombre(txf_Nombre4.getText());
        }
        else{
            errores = true;
            errors += "Falta nombre de los personajes\n";
        }
        if (cmb_TipoPersonaje1.getSelectedIndex() != -1 & cmb_TipoPersonaje2.getSelectedIndex() != -1 & cmb_TipoPersonaje3.getSelectedIndex() != -1 & cmb_TipoPersonaje4.getSelectedIndex() != -1){
            
            Personajes[0].setTipo(ConfirmaTipo(cmb_TipoPersonaje1.getSelectedIndex()));
            Personajes[1].setTipo(ConfirmaTipo(cmb_TipoPersonaje2.getSelectedIndex()));
            Personajes[2].setTipo(ConfirmaTipo(cmb_TipoPersonaje3.getSelectedIndex()));
            Personajes[3].setTipo(ConfirmaTipo(cmb_TipoPersonaje4.getSelectedIndex()));
        }
        else{
            errores = true;
            errors += "Falta especificacion de tipos de personaje\n";
        }
        if (txf_DireccionApariencia1.getText().length() != 0 & txf_DireccionApariencia2.getText().length() != 0 & txf_DireccionApariencia3.getText().length() != 0 & txf_DireccionApariencia4.getText().length() != 0){
            try {
                BufferedImage bufferedImage= ImageIO.read(new File(txf_DireccionApariencia1.getText()));     
                ImageIcon Imagen = new ImageIcon(bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT));
                this.Personajes[0].setApariencia(Imagen);
                bufferedImage= ImageIO.read(new File(txf_DireccionApariencia2.getText()));     
                Imagen = new ImageIcon(bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT));
                this.Personajes[1].setApariencia(Imagen);
                bufferedImage= ImageIO.read(new File(txf_DireccionApariencia3.getText()));     
                Imagen = new ImageIcon(bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT));
                this.Personajes[2].setApariencia(Imagen);
                bufferedImage= ImageIO.read(new File(txf_DireccionApariencia4.getText()));     
                Imagen = new ImageIcon(bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT));
                this.Personajes[3].setApariencia(Imagen);
            }catch (IOException ex) {
                Logger.getLogger(CrearPersonaje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            errores = true;
            errors += "Falta apariencia de personajes\n";
        }
        if (ArmasPersonaje[0] & ArmasPersonaje[1] & ArmasPersonaje[2] & ArmasPersonaje[3]){
            System.out.println("****");
            System.out.println(Armas[0][0].getDaño()[0]);
            System.out.println("****");
            Personajes[0].setArmas(Armas[0]);
            Personajes[1].setArmas(Armas[1]);
            Personajes[2].setArmas(Armas[2]);
            Personajes[3].setArmas(Armas[3]);
        }
        else{
            errores = true;
            errors += "Falta generar armas\n";
        }
        
        if(!errores){
            try {
                Pantalla p = new Pantalla(cliente);
                cliente.pantalla = p;
                p.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(CrearPersonaje.class.getName()).log(Level.SEVERE, null, ex);
            }
}
=======
        if(Contador == 4){
            new Pantalla(cliente).setVisible(true);}
>>>>>>> master
        else{
            JOptionPane.showMessageDialog(this, "Solo se permiten 4 personajes",
               "Errores", JOptionPane.ERROR_MESSAGE);
        }
        
            // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpezarActionPerformed

    private void cmb_TipoPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TipoPersonaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TipoPersonaje1ActionPerformed

    private void btn_VerEstadisticasPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje1ActionPerformed
        Arma[] armas = new Arma[5];
        boolean errores = false;
        if (txf_Arma1Personaje1.getText().length() != 0){
            Arma arma1 = new Arma(txf_Arma1Personaje1.getText());
            lst_StatsArma1Personaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma1.getDaño()[0], "Aire - "+arma1.getDaño()[1],
                                                "Agua - "+arma1.getDaño()[2], "Magia Blanca - "+arma1.getDaño()[3],
                                                "Magia Negra - "+arma1.getDaño()[4], "Electricidad - "+arma1.getDaño()[5],
                                                "Hielo - "+arma1.getDaño()[6], "Acido - "+arma1.getDaño()[7],
                                                "Espiritual - "+arma1.getDaño()[8], "Hierro - "+arma1.getDaño()[9] }));
            armas[0] = arma1;
        }else{errores = true;}
        if (txf_Arma2Personaje1.getText().length() != 0){
            Arma arma2 = new Arma(txf_Arma2Personaje1.getText());
            lst_StatsArma2Personaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma2.getDaño()[0], "Aire - "+arma2.getDaño()[1],
                                                "Agua - "+arma2.getDaño()[2], "Magia Blanca - "+arma2.getDaño()[3],
                                                "Magia Negra - "+arma2.getDaño()[4], "Electricidad - "+arma2.getDaño()[5],
                                                "Hielo - "+arma2.getDaño()[6], "Acido - "+arma2.getDaño()[7],
                                                "Espiritual - "+arma2.getDaño()[8], "Hierro - "+arma2.getDaño()[9] }));
            armas[1] = arma2;
        }else{errores = true;}
        if (txf_Arma3Personaje1.getText().length() != 0){
            Arma arma3 = new Arma(txf_Arma3Personaje1.getText());
            lst_StatsArma3Personaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma3.getDaño()[0], "Aire - "+arma3.getDaño()[1],
                                                "Agua - "+arma3.getDaño()[2], "Magia Blanca - "+arma3.getDaño()[3],
                                                "Magia Negra - "+arma3.getDaño()[4], "Electricidad - "+arma3.getDaño()[5],
                                                "Hielo - "+arma3.getDaño()[6], "Acido - "+arma3.getDaño()[7],
                                                "Espiritual - "+arma3.getDaño()[8], "Hierro - "+arma3.getDaño()[9] }));
            armas[2] = arma3;
        }else{errores = true;}
        if (txf_Arma4Personaje1.getText().length() != 0){
            Arma arma4 = new Arma(txf_Arma4Personaje1.getText());
            lst_StatsArma4Personaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma4.getDaño()[0], "Aire - "+arma4.getDaño()[1],
                                                "Agua - "+arma4.getDaño()[2], "Magia Blanca - "+arma4.getDaño()[3],
                                                "Magia Negra - "+arma4.getDaño()[4], "Electricidad - "+arma4.getDaño()[5],
                                                "Hielo - "+arma4.getDaño()[6], "Acido - "+arma4.getDaño()[7],
                                                "Espiritual - "+arma4.getDaño()[8], "Hierro - "+arma4.getDaño()[9] }));
            armas[3] = arma4;
        }else{errores = true;}
        if (txf_Arma5Personaje1.getText().length() != 0){
            Arma arma5 = new Arma(txf_Arma5Personaje1.getText());
            lst_StatsArma5Personaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma5.getDaño()[0], "Aire - "+arma5.getDaño()[1],
                                                "Agua - "+arma5.getDaño()[2], "Magia Blanca - "+arma5.getDaño()[3],
                                                "Magia Negra - "+arma5.getDaño()[4], "Electricidad - "+arma5.getDaño()[5],
                                                "Hielo - "+arma5.getDaño()[6], "Acido - "+arma5.getDaño()[7],
                                                "Espiritual - "+arma5.getDaño()[8], "Hierro - "+arma5.getDaño()[9] }));
            armas[4] = arma5;
        }else{errores = true;}
        if (!errores){
            this.Armas = armas;
            lbl_ErrorArma1.setText("");
            ArmasPersonaje[0] =  true;
        }
        else{
            ArmasPersonaje[0] = false;
            lbl_ErrorArma1.setVisible(true);
            lbl_ErrorArma1.setText("Faltan Armas");
        }        
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje1ActionPerformed

<<<<<<< HEAD
    private void btn_VerEstadisticasPersonaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje2ActionPerformed
        Arma[] armas = new Arma[5];
        boolean errores = false;
        if (txf_Arma1Personaje2.getText().length() != 0){
            Arma arma1 = new Arma(txf_Arma1Personaje2.getText());
            lst_StatsArma1Personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma1.getDaño()[0], "Aire - "+arma1.getDaño()[1],
                                                "Agua - "+arma1.getDaño()[2], "Magia Blanca - "+arma1.getDaño()[3],
                                                "Magia Negra - "+arma1.getDaño()[4], "Electricidad - "+arma1.getDaño()[5],
                                                "Hielo - "+arma1.getDaño()[6], "Acido - "+arma1.getDaño()[7],
                                                "Espiritual - "+arma1.getDaño()[8], "Hierro - "+arma1.getDaño()[9] }));
            armas[0] = arma1;
        }else{errores = true;}
        if (txf_Arma2Personaje2.getText().length() != 0){
            Arma arma2 = new Arma(txf_Arma2Personaje2.getText());
            lst_StatsArma2Personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma2.getDaño()[0], "Aire - "+arma2.getDaño()[1],
                                                "Agua - "+arma2.getDaño()[2], "Magia Blanca - "+arma2.getDaño()[3],
                                                "Magia Negra - "+arma2.getDaño()[4], "Electricidad - "+arma2.getDaño()[5],
                                                "Hielo - "+arma2.getDaño()[6], "Acido - "+arma2.getDaño()[7],
                                                "Espiritual - "+arma2.getDaño()[8], "Hierro - "+arma2.getDaño()[9] }));
            armas[1] = arma2;
        }else{errores = true;}
        if (txf_Arma3Personaje2.getText().length() != 0){
            Arma arma3 = new Arma(txf_Arma3Personaje2.getText());
            lst_StatsArma3Personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma3.getDaño()[0], "Aire - "+arma3.getDaño()[1],
                                                "Agua - "+arma3.getDaño()[2], "Magia Blanca - "+arma3.getDaño()[3],
                                                "Magia Negra - "+arma3.getDaño()[4], "Electricidad - "+arma3.getDaño()[5],
                                                "Hielo - "+arma3.getDaño()[6], "Acido - "+arma3.getDaño()[7],
                                                "Espiritual - "+arma3.getDaño()[8], "Hierro - "+arma3.getDaño()[9] }));
            armas[2] = arma3;
        }else{errores = true;}

        if (txf_Arma4Personaje2.getText().length() != 0){
            Arma arma4 = new Arma(txf_Arma4Personaje2.getText());
            lst_StatsArma4Personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma4.getDaño()[0], "Aire - "+arma4.getDaño()[1],
                                                "Agua - "+arma4.getDaño()[2], "Magia Blanca - "+arma4.getDaño()[3],
                                                "Magia Negra - "+arma4.getDaño()[4], "Electricidad - "+arma4.getDaño()[5],
                                                "Hielo - "+arma4.getDaño()[6], "Acido - "+arma4.getDaño()[7],
                                                "Espiritual - "+arma4.getDaño()[8], "Hierro - "+arma4.getDaño()[9]}));
            armas[3] = arma4;
        }else{errores = true;}

        if (txf_Arma5Personaje2.getText().length() != 0){
            Arma arma5 = new Arma(txf_Arma5Personaje2.getText());
            lst_StatsArma5Personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma5.getDaño()[0], "Aire - "+arma5.getDaño()[1],
                                                "Agua - "+arma5.getDaño()[2], "Magia Blanca - "+arma5.getDaño()[3],
                                                "Magia Negra - "+arma5.getDaño()[4], "Electricidad - "+arma5.getDaño()[5],
                                                "Hielo - "+arma5.getDaño()[6], "Acido - "+arma5.getDaño()[7],
                                                "Espiritual - "+arma5.getDaño()[8], "Hierro - "+arma5.getDaño()[9] }));
            armas[4] = arma5;
        }else{errores = true;}
        if (!errores){
            this.Armas[1] = armas;
            lbl_ErrorArma2.setText("");
            ArmasPersonaje[1] = true;
        }
        else{
            ArmasPersonaje[1] = false;
            lbl_ErrorArma2.setVisible(true);
            lbl_ErrorArma2.setText("Faltan Armas");
        }
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje2ActionPerformed

    private void btn_VerEstadisticasPersonaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje3ActionPerformed
        Arma[] armas = new Arma[5];
        boolean errores = false;
        if (txf_Arma1Personaje3.getText().length() != 0){
            Arma arma1 = new Arma(txf_Arma1Personaje3.getText());
            lst_StatsArma1Personaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma1.getDaño()[0], "Aire - "+arma1.getDaño()[1],
                                                "Agua - "+arma1.getDaño()[2], "Magia Blanca - "+arma1.getDaño()[3],
                                                "Magia Negra - "+arma1.getDaño()[4], "Electricidad - "+arma1.getDaño()[5],
                                                "Hielo - "+arma1.getDaño()[6], "Acido - "+arma1.getDaño()[7],
                                                "Espiritual - "+arma1.getDaño()[8], "Hierro - "+arma1.getDaño()[9]}));
            armas[0] = arma1;
        }else{errores = true;}
        if (txf_Arma2Personaje3.getText().length() != 0){
            Arma arma2 = new Arma(txf_Arma2Personaje3.getText());
            lst_StatsArma2Personaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma2.getDaño()[0], "Aire - "+arma2.getDaño()[1],
                                                "Agua - "+arma2.getDaño()[2], "Magia Blanca - "+arma2.getDaño()[3],
                                                "Magia Negra - "+arma2.getDaño()[4], "Electricidad - "+arma2.getDaño()[5],
                                                "Hielo - "+arma2.getDaño()[6], "Acido - "+arma2.getDaño()[7],
                                                "Espiritual - "+arma2.getDaño()[8], "Hierro - "+arma2.getDaño()[9] }));
            armas[1] = arma2;
        }else{errores = true;}
        if (txf_Arma3Personaje3.getText().length() != 0){
            Arma arma3 = new Arma(txf_Arma3Personaje3.getText());
            lst_StatsArma3Personaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma3.getDaño()[0], "Aire - "+arma3.getDaño()[1],
                                                "Agua - "+arma3.getDaño()[2], "Magia Blanca - "+arma3.getDaño()[3],
                                                "Magia Negra - "+arma3.getDaño()[4], "Electricidad - "+arma3.getDaño()[5],
                                                "Hielo - "+arma3.getDaño()[6], "Acido - "+arma3.getDaño()[7],
                                                "Espiritual - "+arma3.getDaño()[8], "Hierro - "+arma3.getDaño()[9] }));
            armas[2] = arma3;
        }else{errores = true;}
        if (txf_Arma4Personaje3.getText().length() != 0){
            Arma arma4 = new Arma(txf_Arma4Personaje3.getText());
            lst_StatsArma4Personaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma4.getDaño()[0], "Aire - "+arma4.getDaño()[1],
                                                "Agua - "+arma4.getDaño()[2], "Magia Blanca - "+arma4.getDaño()[3],
                                                "Magia Negra - "+arma4.getDaño()[4], "Electricidad - "+arma4.getDaño()[5],
                                                "Hielo - "+arma4.getDaño()[6], "Acido - "+arma4.getDaño()[7],
                                                "Espiritual - "+arma4.getDaño()[8], "Hierro - "+arma4.getDaño()[9] }));
            armas[3] = arma4;
        }else{errores = true;}
        if (txf_Arma5Personaje3.getText().length() != 0){
            Arma arma5 = new Arma(txf_Arma5Personaje3.getText());
            lst_StatsArma5Personaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma5.getDaño()[0], "Aire - "+arma5.getDaño()[1],
                                                "Agua - "+arma5.getDaño()[2], "Magia Blanca - "+arma5.getDaño()[3],
                                                "Magia Negra - "+arma5.getDaño()[4], "Electricidad - "+arma5.getDaño()[5],
                                                "Hielo - "+arma5.getDaño()[6], "Acido - "+arma5.getDaño()[7],
                                                "Espiritual - "+arma5.getDaño()[8], "Hierro - "+arma5.getDaño()[9] }));
            armas[4] = arma5;
        }else{errores = true;}
        if (!errores){
            this.Armas[2] = armas;
            lbl_ErrorArma3.setText("");
            ArmasPersonaje[2] = true;
        }
        else{
            ArmasPersonaje[2] = false;
            lbl_ErrorArma3.setVisible(true);
            lbl_ErrorArma3.setText("Faltan Armas");
        }
        
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje3ActionPerformed

    private void btn_VerEstadisticasPersonaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje4ActionPerformed
        Arma[] armas = new Arma[5];
        boolean errores = false;
        if (txf_Arma1Personaje4.getText().length() != 0){
            Arma arma1 = new Arma(txf_Arma1Personaje4.getText());
            lst_StatsArma1Personaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma1.getDaño()[0], "Aire - "+arma1.getDaño()[1],
                                                "Agua - "+arma1.getDaño()[2], "Magia Blanca - "+arma1.getDaño()[3],
                                                "Magia Negra - "+arma1.getDaño()[4], "Electricidad - "+arma1.getDaño()[5],
                                                "Hielo - "+arma1.getDaño()[6], "Acido - "+arma1.getDaño()[7],
                                                "Espiritual - "+arma1.getDaño()[8], "Hierro - "+arma1.getDaño()[9]}));
            armas[0] = arma1;
        }else{errores = true;}
        if (txf_Arma2Personaje4.getText().length() != 0){
            Arma arma2 = new Arma(txf_Arma2Personaje4.getText());
            lst_StatsArma2Personaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma2.getDaño()[0], "Aire - "+arma2.getDaño()[1],
                                                "Agua - "+arma2.getDaño()[2], "Magia Blanca - "+arma2.getDaño()[3],
                                                "Magia Negra - "+arma2.getDaño()[4], "Electricidad - "+arma2.getDaño()[5],
                                                "Hielo - "+arma2.getDaño()[6], "Acido - "+arma2.getDaño()[7],
                                                "Espiritual - "+arma2.getDaño()[8], "Hierro - "+arma2.getDaño()[9] }));
            armas[1] = arma2;
        }else{errores = true;}
        if (txf_Arma3Personaje4.getText().length() != 0){
            Arma arma3 = new Arma(txf_Arma3Personaje4.getText());
            lst_StatsArma3Personaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma3.getDaño()[0], "Aire - "+arma3.getDaño()[1],
                                                "Agua - "+arma3.getDaño()[2], "Magia Blanca - "+arma3.getDaño()[3],
                                                "Magia Negra - "+arma3.getDaño()[4], "Electricidad - "+arma3.getDaño()[5],
                                                "Hielo - "+arma3.getDaño()[6], "Acido - "+arma3.getDaño()[7],
                                                "Espiritual - "+arma3.getDaño()[8], "Hierro - "+arma3.getDaño()[9] }));
            armas[2] = arma3;
        }else{errores = true;}
        if (txf_Arma4Personaje4.getText().length() != 0){
            Arma arma4 = new Arma(txf_Arma4Personaje4.getText());
            lst_StatsArma4Personaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma4.getDaño()[0], "Aire - "+arma4.getDaño()[1],
                                                "Agua - "+arma4.getDaño()[2], "Magia Blanca - "+arma4.getDaño()[3],
                                                "Magia Negra - "+arma4.getDaño()[4], "Electricidad - "+arma4.getDaño()[5],
                                                "Hielo - "+arma4.getDaño()[6], "Acido - "+arma4.getDaño()[7],
                                                "Espiritual - "+arma4.getDaño()[8], "Hierro - "+arma4.getDaño()[9] }));
            armas[3] = arma4;
        }else{errores = true;}
        if (txf_Arma5Personaje4.getText().length() != 0){
            Arma arma5 = new Arma(txf_Arma5Personaje4.getText());
            lst_StatsArma5Personaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
                                                "Fuego - "+arma5.getDaño()[0], "Aire - "+arma5.getDaño()[1],
                                                "Agua - "+arma5.getDaño()[2], "Magia Blanca - "+arma5.getDaño()[3],
                                                "Magia Negra - "+arma5.getDaño()[4], "Electricidad - "+arma5.getDaño()[5],
                                                "Hielo - "+arma5.getDaño()[6], "Acido - "+arma5.getDaño()[7],
                                                "Espiritual - "+arma5.getDaño()[8], "Hierro - "+arma5.getDaño()[9]}));
            armas[4] = arma5;
        }else{errores = true;}
        if (!errores){
            this.Armas[3] = armas;
            lbl_ErrorArma4.setText("");
            ArmasPersonaje[3] = true;
        }
        else{
            ArmasPersonaje[3] = false;
            lbl_ErrorArma4.setVisible(true);
            lbl_ErrorArma4.setText("Faltan Armas");
        }
              
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje4ActionPerformed

=======
>>>>>>> master
    private void btn_VerPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerPersonaje1ActionPerformed
        try{
            String direccion = txf_Apariencia1.getText();
            BufferedImage bufferedImage= ImageIO.read(new File(direccion));
            Image image = bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(image);
            lbl_Apariencia1.setText("");
            lbl_Apariencia1.setIcon (icon);
        }catch(Exception e){}
    }//GEN-LAST:event_btn_VerPersonaje1ActionPerformed

    private void txf_Arma2Personaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Arma2Personaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Arma2Personaje1ActionPerformed

    private void txf_Arma1Personaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Arma1Personaje1ActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Arma1Personaje1ActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if(lst_personajes.getSelectedIndex() != -1){
            Personajes[lst_personajes.getSelectedIndex()] = null;
            Contador--;
            Personajes = f.OrdenarArrayPersonajes(Personajes);
            lst_personajes.setModel(new javax.swing.DefaultComboBoxModel<>(f.PersonajeArraytoStringArray(Personajes)));        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (Contador == 4){
            JOptionPane.showMessageDialog(this, "Ya no se pueden agregar mas personajes",
               "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String str = "%";
            String errors = "";
            boolean errores = false;
            if (txf_Nombre1.getText().length() != 0){
                str += txf_Nombre1.getText()+"/";
            }else{errores = true;    errors += "Falta el nombre de personaje\n";}
            if (cmb_TipoPersonaje1.getSelectedIndex() != -1){
                str += cmb_TipoPersonaje1.getSelectedIndex()+"/";
            }else {errores = true;
                errors += "Falta especificacion de tipo de personaje\n";}
            if (txf_Apariencia1.getText().length() != 0){
                str+= txf_Apariencia1.getText()+"/";
            }else {errores = true; 
                errors += "Falta direccion de la apariencia\n";}
            if (txf_Arma1Personaje1.getText().length() != 0){
                str += txf_Arma1Personaje1.getText()+"$";
            }else{errores = true;
                errors += "Falta generar arma 1\n";}        
            if (txf_Arma2Personaje1.getText().length() != 0){
                str += txf_Arma2Personaje1.getText()+"$";
            }else{errores = true;    
                errors += "Falta generar arma 2\n";}
            if (txf_Arma3Personaje1.getText().length() != 0){
                str += txf_Arma3Personaje1.getText()+"$";
            }else{errores = true;    
                errors += "Falta generar arma 3\n";}
            if (txf_Arma4Personaje1.getText().length() != 0){
                str += txf_Arma4Personaje1.getText()+"$";
            }else{errores = true;
                errors += "Falta generar arma 4\n";}
            if (txf_Arma5Personaje1.getText().length() != 0){
                str += txf_Arma5Personaje1.getText();
            }else {errores = true;
                errors += "Falta generar arma 5\n";}
            if (!errores){
                System.out.println(str);
                FileWriter escritor;
                try {
                    escritor = new FileWriter("Personajes.txt",true); 
                    escritor.write(str);
                    escritor.close();

                    //Cambiar 
                    Arma[] a = new Arma[5];
                    try{
                        String direccion = txf_Apariencia1.getText();
                        BufferedImage bufferedImage= ImageIO.read(new File(direccion));
                        Image image = bufferedImage.getScaledInstance(140, 150, Image.SCALE_DEFAULT);
                        ImageIcon icon = new ImageIcon(image);
                        Personajes[Contador] = new Personaje(txf_Nombre1.getText(),ConfirmaTipo(cmb_TipoPersonaje1.getSelectedIndex()),a,icon,direccion,cmb_TipoPersonaje1.getSelectedIndex());                
                        Contador++;
                    }catch(Exception e){}
                    //

                    lst_personajes.setModel(new javax.swing.DefaultComboBoxModel<>(f.PersonajeArraytoStringArray(Personajes)));        
                } catch (IOException ex) {
                    Logger.getLogger(CrearPersonaje.class.getName()).log(Level.SEVERE, null, ex);
                }
                lbl_ErrorArma1.setText("");
                ArmasPersonaje[0] =  true;
            }
            else{
                JOptionPane.showMessageDialog(this, errors,
                   "Errores", JOptionPane.ERROR_MESSAGE);
            }     
        }
    }//GEN-LAST:event_btn_agregarActionPerformed


    private void cmb_NombresPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_NombresPersonajesActionPerformed
        txf_Nombre1.setText((String)cmb_NombresPersonajes.getSelectedItem());
        txf_Arma1Personaje1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getArmas()[0].getNombre());
        txf_Arma2Personaje1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getArmas()[1].getNombre());        
        txf_Arma3Personaje1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getArmas()[2].getNombre());
        txf_Arma4Personaje1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getArmas()[3].getNombre());
        txf_Arma5Personaje1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getArmas()[4].getNombre());
     
        lbl_Apariencia1.setIcon(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getApariencia());
        lbl_Apariencia1.setText("");
        txf_Apariencia1.setText(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getDireccion());
       cmb_TipoPersonaje1.setSelectedIndex(PersonajesArchivo[cmb_NombresPersonajes.getSelectedIndex()].getPosTipo());
        
    }//GEN-LAST:event_cmb_NombresPersonajesActionPerformed


    public void read_personajes(){
        
        try{
            File file = new File("Personajes.txt");
            BufferedReader Lector = new BufferedReader(new FileReader(file));
            String archivo;
            archivo = Lector.readLine();
            if (archivo != null){
                String[] personajes_archivo= archivo.split("%");
                int cont = 0;
                this.PersonajesArchivo = new Personaje[personajes_archivo.length];
                for (String personaje : personajes_archivo){
                    String[] parametro = personaje.split("/");
                    if (parametro.length == 4){
                        Arma[] armas_temp = new Arma[5];
                        System.out.println(parametro[3]);
                        String[] ArmasArchivo = parametro[3].split("\\$");
                        
                        System.out.println(ArmasArchivo.length);
                        if (ArmasArchivo.length == 5){
                            armas_temp[0] = new Arma(ArmasArchivo[0]);
                            armas_temp[1] = new Arma(ArmasArchivo[1]);
                            armas_temp[2] = new Arma(ArmasArchivo[2]);
                            armas_temp[3] = new Arma(ArmasArchivo[3]);
                            armas_temp[4] = new Arma(ArmasArchivo[4]);

                            BufferedImage bufferedImage= ImageIO.read(new File(parametro[2]));
                            Image image = bufferedImage.getScaledInstance(100, 120, Image.SCALE_DEFAULT);
                            Tipo temp = ConfirmaTipo(Integer.parseInt(parametro[1]));
                            this.PersonajesArchivo[cont] = (new Personaje(parametro[0],temp, armas_temp, new ImageIcon(image),parametro[2],Integer.parseInt(parametro[1])));
                            cont++;
                        }
                    }
                }
            }
        }catch(IOException | NumberFormatException e){}
    }
    public Tipo ConfirmaTipo(int posicion){
        return switch (posicion) {
            case 0 -> Tipo.FUEGO;
            case 1 -> Tipo.AIRE;
            case 2 -> Tipo.AGUA;
            case 3 -> Tipo.MAGIABLANCA;
            case 4 -> Tipo.MAGIANEGRA;
            case 5 -> Tipo.ELECTRICIDAD;
            case 6 -> Tipo.HIELO;
            case 7 -> Tipo.ACIDO;
            case 8 -> Tipo.ESPIRITUAL;
            case 9 -> Tipo.HIERRO;
            default -> null;
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente client = new Cliente();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Empezar;
    public javax.swing.JButton btn_VerEstadisticasPersonaje1;
    public javax.swing.JButton btn_VerPersonaje1;
    public javax.swing.JButton btn_agregar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JComboBox<String> cmb_NombresPersonajes;
    public javax.swing.JComboBox<String> cmb_TipoPersonaje1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lbl_Apariencia1;
    public javax.swing.JLabel lbl_Armas;
    public javax.swing.JLabel lbl_DireccionApariencia1;
    public javax.swing.JLabel lbl_ErrorArma1;
    public javax.swing.JLabel lbl_TipoPersonaje1;
    public javax.swing.JLabel lbl_nombre1;
    public javax.swing.JList<String> lst_StatsArma1Personaje1;
    public javax.swing.JList<String> lst_StatsArma2Personaje1;
    public javax.swing.JList<String> lst_StatsArma3Personaje1;
    public javax.swing.JList<String> lst_StatsArma4Personaje1;
    public javax.swing.JList<String> lst_StatsArma5Personaje1;
    public javax.swing.JList<String> lst_personajes;
    public javax.swing.JPanel pnl_Personaje1;
    public javax.swing.JTextField txf_Apariencia1;
    public javax.swing.JTextField txf_Arma1Personaje1;
    public javax.swing.JTextField txf_Arma2Personaje1;
    public javax.swing.JTextField txf_Arma3Personaje1;
    public javax.swing.JTextField txf_Arma4Personaje1;
    public javax.swing.JTextField txf_Arma5Personaje1;
    public javax.swing.JTextField txf_Nombre1;
    // End of variables declaration//GEN-END:variables
}
