/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Personaje;

/**
 *
 * @author jecheverria
 */
public class CrearPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form CrearPersonaje
     */
    public CrearPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Personaje1 = new javax.swing.JPanel();
        txf_Arma2Personaje1 = new javax.swing.JTextField();
        txf_Arma3Personaje1 = new javax.swing.JTextField();
        txf_Arma4Personaje1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_StatsArma1Personaje1 = new javax.swing.JList<>();
        txf_Arma5Personaje1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_StatsArma2Personaje1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_StatsArma3Personaje1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_StatsArma4Personaje1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_StatsArma5Personaje1 = new javax.swing.JList<>();
        btn_VerEstadisticasPersonaje1 = new javax.swing.JButton();
        lbl_Armas = new javax.swing.JLabel();
        txf_Arma1Personaje1 = new javax.swing.JTextField();
        lbl_Apariencia1 = new javax.swing.JLabel();
        txf_DireccionApariencia1 = new javax.swing.JTextField();
        lbl_DireccionApariencia1 = new javax.swing.JLabel();
        btn_VerPersonaje1 = new javax.swing.JButton();
        lbl_nombre1 = new javax.swing.JLabel();
        txf_Nombre1 = new javax.swing.JTextField();
        cmb_TipoPersonaje1 = new javax.swing.JComboBox<>();
        lbl_TipoPersonaje1 = new javax.swing.JLabel();
        pnl_Personaje2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lst_StatsArma1Personaje2 = new javax.swing.JList<>();
        txf_Arma5Personaje2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        lst_StatsArma2Personaje2 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        lst_StatsArma3Personaje2 = new javax.swing.JList<>();
        btn_VerEstadisticasPersonaje2 = new javax.swing.JButton();
        lbl_Armas1 = new javax.swing.JLabel();
        txf_Arma1Personaje2 = new javax.swing.JTextField();
        txf_Arma2Personaje2 = new javax.swing.JTextField();
        txf_Arma3Personaje2 = new javax.swing.JTextField();
        txf_Arma4Personaje2 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        lst_StatsArma4Personaje2 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        lst_StatsArma5Personaje2 = new javax.swing.JList<>();
        txf_DireccionApariencia2 = new javax.swing.JTextField();
        lbl_Apariencia2 = new javax.swing.JLabel();
        lbl_DireccionApariencia2 = new javax.swing.JLabel();
        btn_VerPersonaje2 = new javax.swing.JButton();
        lbl_nombre2 = new javax.swing.JLabel();
        txf_Nombre2 = new javax.swing.JTextField();
        cmb_TipoPersonaje2 = new javax.swing.JComboBox<>();
        lbl_TipoPersonaje2 = new javax.swing.JLabel();
        pnl_Personaje3 = new javax.swing.JPanel();
        lbl_Armas2 = new javax.swing.JLabel();
        txf_Arma1Personaje3 = new javax.swing.JTextField();
        txf_Arma2Personaje3 = new javax.swing.JTextField();
        txf_Arma3Personaje3 = new javax.swing.JTextField();
        txf_Arma4Personaje3 = new javax.swing.JTextField();
        jScrollPane14 = new javax.swing.JScrollPane();
        lst_StatsArma4Personaje3 = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        lst_StatsArma5Personaje3 = new javax.swing.JList<>();
        btn_VerEstadisticasPersonaje3 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        lst_StatsArma1Personaje3 = new javax.swing.JList<>();
        txf_Arma5Personaje3 = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        lst_StatsArma2Personaje3 = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        lst_StatsArma3Personaje3 = new javax.swing.JList<>();
        txf_DireccionApariencia3 = new javax.swing.JTextField();
        lbl_Apariencia3 = new javax.swing.JLabel();
        lbl_DireccionApariencia3 = new javax.swing.JLabel();
        btn_VerPersonaje3 = new javax.swing.JButton();
        lbl_nombre3 = new javax.swing.JLabel();
        txf_Nombre3 = new javax.swing.JTextField();
        cmb_TipoPersonaje3 = new javax.swing.JComboBox<>();
        lbl_TipoPersonaje3 = new javax.swing.JLabel();
        pnl_Personaje4 = new javax.swing.JPanel();
        txf_Arma2Personaje4 = new javax.swing.JTextField();
        txf_Arma3Personaje4 = new javax.swing.JTextField();
        txf_Arma4Personaje4 = new javax.swing.JTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        lst_StatsArma4Personaje4 = new javax.swing.JList<>();
        jScrollPane17 = new javax.swing.JScrollPane();
        lst_StatsArma5Personaje4 = new javax.swing.JList<>();
        jScrollPane18 = new javax.swing.JScrollPane();
        lst_StatsArma1Personaje4 = new javax.swing.JList<>();
        txf_Arma5Personaje4 = new javax.swing.JTextField();
        jScrollPane19 = new javax.swing.JScrollPane();
        lst_StatsArma2Personaje4 = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        lst_StatsArma3Personaje4 = new javax.swing.JList<>();
        lbl_Armas3 = new javax.swing.JLabel();
        txf_Arma1Personaje4 = new javax.swing.JTextField();
        btn_VerEstadisticasPersonaje4 = new javax.swing.JButton();
        txf_DireccionApariencia4 = new javax.swing.JTextField();
        lbl_Apariencia4 = new javax.swing.JLabel();
        lbl_DireccionApariencia4 = new javax.swing.JLabel();
        btn_VerPersonaje4 = new javax.swing.JButton();
        lbl_nombre4 = new javax.swing.JLabel();
        txf_Nombre4 = new javax.swing.JTextField();
        cmb_TipoPersonaje4 = new javax.swing.JComboBox<>();
        lbl_TipoPersonaje4 = new javax.swing.JLabel();
        btn_Empezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Personaje1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        lst_StatsArma1Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_StatsArma1Personaje1);

        lst_StatsArma2Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lst_StatsArma2Personaje1);

        lst_StatsArma3Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_StatsArma3Personaje1);

        lst_StatsArma4Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lst_StatsArma4Personaje1);

        lst_StatsArma5Personaje1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lst_StatsArma5Personaje1);

        btn_VerEstadisticasPersonaje1.setText("Ver estadisticas");
        btn_VerEstadisticasPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerEstadisticasPersonaje1ActionPerformed(evt);
            }
        });

        lbl_Armas.setText("Armas:");

        lbl_Apariencia1.setText("<Imagen apariencia>");

        txf_DireccionApariencia1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txf_DireccionApariencia1.setText("C:\\Users\\jecheverria\\Apariencias\\");
            txf_DireccionApariencia1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txf_DireccionApariencia1ActionPerformed(evt);
                }
            });

            lbl_DireccionApariencia1.setText("Direccion de apariencia");

            btn_VerPersonaje1.setText("Ver");

            lbl_nombre1.setText("Nombre de personaje:");

            cmb_TipoPersonaje1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " }));
            cmb_TipoPersonaje1.setSelectedIndex(-1);
            cmb_TipoPersonaje1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmb_TipoPersonaje1ActionPerformed(evt);
                }
            });

            lbl_TipoPersonaje1.setText("Tipo:");

            javax.swing.GroupLayout pnl_Personaje1Layout = new javax.swing.GroupLayout(pnl_Personaje1);
            pnl_Personaje1.setLayout(pnl_Personaje1Layout);
            pnl_Personaje1Layout.setHorizontalGroup(
                pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txf_Arma5Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2)
                                            .addComponent(txf_Arma3Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txf_Arma1Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txf_Arma4Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txf_Arma2Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                    .addComponent(lbl_Armas)
                                    .addGap(7, 7, 7)
                                    .addComponent(btn_VerEstadisticasPersonaje1))
                                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                    .addComponent(lbl_DireccionApariencia1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_VerPersonaje1))
                                .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txf_Nombre1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_nombre1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(cmb_TipoPersonaje1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbl_TipoPersonaje1)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addComponent(txf_DireccionApariencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnl_Personaje1Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(lbl_Apariencia1)))
                    .addContainerGap())
            );
            pnl_Personaje1Layout.setVerticalGroup(
                pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nombre1)
                        .addComponent(lbl_TipoPersonaje1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txf_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_TipoPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_DireccionApariencia1)
                        .addComponent(btn_VerPersonaje1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txf_DireccionApariencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                    .addComponent(lbl_Apariencia1)
                    .addGap(110, 110, 110)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_Armas)
                        .addComponent(btn_VerEstadisticasPersonaje1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txf_Arma2Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txf_Arma1Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txf_Arma4Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txf_Arma3Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnl_Personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txf_Arma5Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pnl_Personaje2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

            lst_StatsArma1Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane6.setViewportView(lst_StatsArma1Personaje2);

            lst_StatsArma2Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane7.setViewportView(lst_StatsArma2Personaje2);

            lst_StatsArma3Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane8.setViewportView(lst_StatsArma3Personaje2);

            btn_VerEstadisticasPersonaje2.setText("Ver estadisticas");
            btn_VerEstadisticasPersonaje2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_VerEstadisticasPersonaje2ActionPerformed(evt);
                }
            });

            lbl_Armas1.setText("Armas:");

            lst_StatsArma4Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane9.setViewportView(lst_StatsArma4Personaje2);

            lst_StatsArma5Personaje2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane10.setViewportView(lst_StatsArma5Personaje2);

            txf_DireccionApariencia2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            txf_DireccionApariencia2.setText("C:\\Users\\jecheverria\\Apariencias\\");
                txf_DireccionApariencia2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txf_DireccionApariencia2ActionPerformed(evt);
                    }
                });

                lbl_Apariencia2.setText("<Imagen apariencia>");

                lbl_DireccionApariencia2.setText("Direccion de apariencia");

                btn_VerPersonaje2.setText("Ver");

                lbl_nombre2.setText("Nombre de personaje:");

                cmb_TipoPersonaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " }));
                cmb_TipoPersonaje2.setSelectedIndex(-1);
                cmb_TipoPersonaje2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cmb_TipoPersonaje2ActionPerformed(evt);
                    }
                });

                lbl_TipoPersonaje2.setText("Tipo:");

                javax.swing.GroupLayout pnl_Personaje2Layout = new javax.swing.GroupLayout(pnl_Personaje2);
                pnl_Personaje2.setLayout(pnl_Personaje2Layout);
                pnl_Personaje2Layout.setHorizontalGroup(
                    pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txf_Nombre2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nombre2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_TipoPersonaje2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                                .addComponent(lbl_TipoPersonaje2)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane8)
                                                .addComponent(txf_Arma3Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma4Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma2Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Personaje2Layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma5Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(59, 59, 59)))
                                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                        .addComponent(lbl_Armas1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_VerEstadisticasPersonaje2))
                                    .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                        .addComponent(lbl_DireccionApariencia2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_VerPersonaje2))
                                    .addComponent(txf_DireccionApariencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma1Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_Personaje2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lbl_Apariencia2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnl_Personaje2Layout.setVerticalGroup(
                    pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre2)
                            .addComponent(lbl_TipoPersonaje2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_TipoPersonaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_DireccionApariencia2)
                            .addComponent(btn_VerPersonaje2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_DireccionApariencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Apariencia2)
                        .addGap(109, 109, 109)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Armas1)
                            .addComponent(btn_VerEstadisticasPersonaje2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_Arma1Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Arma2Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_Arma4Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Arma3Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_Arma5Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                pnl_Personaje3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

                lbl_Armas2.setText("Armas:");

                lst_StatsArma4Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane14.setViewportView(lst_StatsArma4Personaje3);

                lst_StatsArma5Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane15.setViewportView(lst_StatsArma5Personaje3);

                btn_VerEstadisticasPersonaje3.setText("Ver estadisticas");
                btn_VerEstadisticasPersonaje3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btn_VerEstadisticasPersonaje3ActionPerformed(evt);
                    }
                });

                lst_StatsArma1Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane11.setViewportView(lst_StatsArma1Personaje3);

                lst_StatsArma2Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane12.setViewportView(lst_StatsArma2Personaje3);

                lst_StatsArma3Personaje3.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane13.setViewportView(lst_StatsArma3Personaje3);

                txf_DireccionApariencia3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
                txf_DireccionApariencia3.setText("C:\\Users\\jecheverria\\Apariencias\\");
                    txf_DireccionApariencia3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txf_DireccionApariencia3ActionPerformed(evt);
                        }
                    });

                    lbl_Apariencia3.setText("<Imagen apariencia>");

                    lbl_DireccionApariencia3.setText("Direccion de apariencia");

                    btn_VerPersonaje3.setText("Ver");

                    lbl_nombre3.setText("Nombre de personaje:");

                    cmb_TipoPersonaje3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " }));
                    cmb_TipoPersonaje3.setSelectedIndex(-1);
                    cmb_TipoPersonaje3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            cmb_TipoPersonaje3ActionPerformed(evt);
                        }
                    });

                    lbl_TipoPersonaje3.setText("Tipo:");

                    javax.swing.GroupLayout pnl_Personaje3Layout = new javax.swing.GroupLayout(pnl_Personaje3);
                    pnl_Personaje3.setLayout(pnl_Personaje3Layout);
                    pnl_Personaje3Layout.setHorizontalGroup(
                        pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txf_Nombre3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_nombre3, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmb_TipoPersonaje3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                                    .addComponent(lbl_TipoPersonaje3)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                            .addGap(56, 56, 56)
                                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma5Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane13)
                                                    .addComponent(txf_Arma3Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txf_Arma1Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma4Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txf_Arma2Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                            .addComponent(lbl_Armas2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_VerEstadisticasPersonaje3))
                                        .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                            .addComponent(lbl_DireccionApariencia3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_VerPersonaje3))
                                        .addComponent(txf_DireccionApariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(lbl_Apariencia3)))
                            .addContainerGap(7, Short.MAX_VALUE))
                    );
                    pnl_Personaje3Layout.setVerticalGroup(
                        pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_Personaje3Layout.createSequentialGroup()
                                    .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_nombre3)
                                        .addComponent(lbl_TipoPersonaje3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txf_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmb_TipoPersonaje3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_VerPersonaje3)
                                .addComponent(lbl_DireccionApariencia3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txf_DireccionApariencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Apariencia3)
                            .addGap(107, 107, 107)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Armas2)
                                .addComponent(btn_VerEstadisticasPersonaje3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txf_Arma2Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_Arma1Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txf_Arma4Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_Arma3Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnl_Personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txf_Arma5Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                    );

                    pnl_Personaje4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));

                    txf_Arma2Personaje4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txf_Arma2Personaje4ActionPerformed(evt);
                        }
                    });

                    lst_StatsArma4Personaje4.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });
                    jScrollPane16.setViewportView(lst_StatsArma4Personaje4);

                    lst_StatsArma5Personaje4.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });
                    jScrollPane17.setViewportView(lst_StatsArma5Personaje4);

                    lst_StatsArma1Personaje4.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });
                    jScrollPane18.setViewportView(lst_StatsArma1Personaje4);

                    lst_StatsArma2Personaje4.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });
                    jScrollPane19.setViewportView(lst_StatsArma2Personaje4);

                    lst_StatsArma3Personaje4.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                    });
                    jScrollPane20.setViewportView(lst_StatsArma3Personaje4);

                    lbl_Armas3.setText("Armas:");

                    btn_VerEstadisticasPersonaje4.setText("Ver estadisticas");
                    btn_VerEstadisticasPersonaje4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btn_VerEstadisticasPersonaje4ActionPerformed(evt);
                        }
                    });

                    txf_DireccionApariencia4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
                    txf_DireccionApariencia4.setText("C:\\Users\\jecheverria\\Apariencias\\");
                        txf_DireccionApariencia4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txf_DireccionApariencia4ActionPerformed(evt);
                            }
                        });

                        lbl_Apariencia4.setText("<Imagen apariencia>");

                        lbl_DireccionApariencia4.setText("Direccion de apariencia");

                        btn_VerPersonaje4.setText("Ver");

                        lbl_nombre4.setText("Nombre de personaje:");

                        cmb_TipoPersonaje4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego -", "Aire -", "Agua -", "Magia Blanca - ", "Magia Negra - ", "Electricidad -", "Hielo - ", "Acido - ", "Espiritual - ", "Hierro - " }));
                        cmb_TipoPersonaje4.setSelectedIndex(-1);
                        cmb_TipoPersonaje4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmb_TipoPersonaje4ActionPerformed(evt);
                            }
                        });

                        lbl_TipoPersonaje4.setText("Tipo:");

                        javax.swing.GroupLayout pnl_Personaje4Layout = new javax.swing.GroupLayout(pnl_Personaje4);
                        pnl_Personaje4.setLayout(pnl_Personaje4Layout);
                        pnl_Personaje4Layout.setHorizontalGroup(
                            pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                        .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txf_Nombre4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nombre4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_TipoPersonaje4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addComponent(lbl_TipoPersonaje4)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                        .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txf_Arma5Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane20)
                                                        .addComponent(txf_Arma3Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txf_Arma1Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txf_Arma4Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txf_Arma2Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addComponent(lbl_Armas3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_VerEstadisticasPersonaje4))
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addComponent(lbl_DireccionApariencia4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_VerPersonaje4))
                                            .addComponent(txf_DireccionApariencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnl_Personaje4Layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(lbl_Apariencia4)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        );
                        pnl_Personaje4Layout.setVerticalGroup(
                            pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Personaje4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_nombre4)
                                    .addComponent(lbl_TipoPersonaje4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txf_Nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_TipoPersonaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_DireccionApariencia4)
                                    .addComponent(btn_VerPersonaje4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_DireccionApariencia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(lbl_Apariencia4)
                                .addGap(114, 114, 114)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Armas3)
                                    .addComponent(btn_VerEstadisticasPersonaje4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txf_Arma2Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma1Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txf_Arma4Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_Arma3Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_Personaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_Arma5Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        );

                        btn_Empezar.setText("Empezar");
                        btn_Empezar.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_EmpezarActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnl_Personaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_Personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_Personaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_Personaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Empezar)
                                .addGap(505, 505, 505))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnl_Personaje4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_Personaje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_Personaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_Personaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Empezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void txf_DireccionApariencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_DireccionApariencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_DireccionApariencia1ActionPerformed

    private void txf_DireccionApariencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_DireccionApariencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_DireccionApariencia2ActionPerformed

    private void txf_DireccionApariencia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_DireccionApariencia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_DireccionApariencia3ActionPerformed

    private void txf_DireccionApariencia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_DireccionApariencia4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_DireccionApariencia4ActionPerformed

    private void txf_Arma1Personaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Arma1Personaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Arma1Personaje4ActionPerformed

    private void txf_Arma2Personaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Arma2Personaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Arma2Personaje4ActionPerformed

    private void btn_EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpezarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpezarActionPerformed

    private void cmb_TipoPersonaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TipoPersonaje3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TipoPersonaje3ActionPerformed

    private void cmb_TipoPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TipoPersonaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TipoPersonaje1ActionPerformed

    private void cmb_TipoPersonaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TipoPersonaje2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TipoPersonaje2ActionPerformed

    private void cmb_TipoPersonaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TipoPersonaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TipoPersonaje4ActionPerformed

    private void btn_VerEstadisticasPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje1ActionPerformed

    private void btn_VerEstadisticasPersonaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje2ActionPerformed

    private void btn_VerEstadisticasPersonaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje3ActionPerformed

    private void btn_VerEstadisticasPersonaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEstadisticasPersonaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerEstadisticasPersonaje4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Empezar;
    public javax.swing.JButton btn_VerEstadisticasPersonaje1;
    public javax.swing.JButton btn_VerEstadisticasPersonaje2;
    public javax.swing.JButton btn_VerEstadisticasPersonaje3;
    public javax.swing.JButton btn_VerEstadisticasPersonaje4;
    public javax.swing.JButton btn_VerPersonaje1;
    public javax.swing.JButton btn_VerPersonaje2;
    public javax.swing.JButton btn_VerPersonaje3;
    public javax.swing.JButton btn_VerPersonaje4;
    public javax.swing.JComboBox<String> cmb_TipoPersonaje1;
    public javax.swing.JComboBox<String> cmb_TipoPersonaje2;
    public javax.swing.JComboBox<String> cmb_TipoPersonaje3;
    public javax.swing.JComboBox<String> cmb_TipoPersonaje4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane16;
    public javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane18;
    public javax.swing.JScrollPane jScrollPane19;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane20;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel lbl_Apariencia1;
    public javax.swing.JLabel lbl_Apariencia2;
    public javax.swing.JLabel lbl_Apariencia3;
    public javax.swing.JLabel lbl_Apariencia4;
    public javax.swing.JLabel lbl_Armas;
    public javax.swing.JLabel lbl_Armas1;
    public javax.swing.JLabel lbl_Armas2;
    public javax.swing.JLabel lbl_Armas3;
    public javax.swing.JLabel lbl_DireccionApariencia1;
    public javax.swing.JLabel lbl_DireccionApariencia2;
    public javax.swing.JLabel lbl_DireccionApariencia3;
    public javax.swing.JLabel lbl_DireccionApariencia4;
    public javax.swing.JLabel lbl_TipoPersonaje1;
    public javax.swing.JLabel lbl_TipoPersonaje2;
    public javax.swing.JLabel lbl_TipoPersonaje3;
    public javax.swing.JLabel lbl_TipoPersonaje4;
    public javax.swing.JLabel lbl_nombre1;
    public javax.swing.JLabel lbl_nombre2;
    public javax.swing.JLabel lbl_nombre3;
    public javax.swing.JLabel lbl_nombre4;
    public javax.swing.JList<String> lst_StatsArma1Personaje1;
    public javax.swing.JList<String> lst_StatsArma1Personaje2;
    public javax.swing.JList<String> lst_StatsArma1Personaje3;
    public javax.swing.JList<String> lst_StatsArma1Personaje4;
    public javax.swing.JList<String> lst_StatsArma2Personaje1;
    public javax.swing.JList<String> lst_StatsArma2Personaje2;
    public javax.swing.JList<String> lst_StatsArma2Personaje3;
    public javax.swing.JList<String> lst_StatsArma2Personaje4;
    public javax.swing.JList<String> lst_StatsArma3Personaje1;
    public javax.swing.JList<String> lst_StatsArma3Personaje2;
    public javax.swing.JList<String> lst_StatsArma3Personaje3;
    public javax.swing.JList<String> lst_StatsArma3Personaje4;
    public javax.swing.JList<String> lst_StatsArma4Personaje1;
    public javax.swing.JList<String> lst_StatsArma4Personaje2;
    public javax.swing.JList<String> lst_StatsArma4Personaje3;
    public javax.swing.JList<String> lst_StatsArma4Personaje4;
    public javax.swing.JList<String> lst_StatsArma5Personaje1;
    public javax.swing.JList<String> lst_StatsArma5Personaje2;
    public javax.swing.JList<String> lst_StatsArma5Personaje3;
    public javax.swing.JList<String> lst_StatsArma5Personaje4;
    public javax.swing.JPanel pnl_Personaje1;
    public javax.swing.JPanel pnl_Personaje2;
    public javax.swing.JPanel pnl_Personaje3;
    public javax.swing.JPanel pnl_Personaje4;
    public javax.swing.JTextField txf_Arma1Personaje1;
    public javax.swing.JTextField txf_Arma1Personaje2;
    public javax.swing.JTextField txf_Arma1Personaje3;
    public javax.swing.JTextField txf_Arma1Personaje4;
    public javax.swing.JTextField txf_Arma2Personaje1;
    public javax.swing.JTextField txf_Arma2Personaje2;
    public javax.swing.JTextField txf_Arma2Personaje3;
    public javax.swing.JTextField txf_Arma2Personaje4;
    public javax.swing.JTextField txf_Arma3Personaje1;
    public javax.swing.JTextField txf_Arma3Personaje2;
    public javax.swing.JTextField txf_Arma3Personaje3;
    public javax.swing.JTextField txf_Arma3Personaje4;
    public javax.swing.JTextField txf_Arma4Personaje1;
    public javax.swing.JTextField txf_Arma4Personaje2;
    public javax.swing.JTextField txf_Arma4Personaje3;
    public javax.swing.JTextField txf_Arma4Personaje4;
    public javax.swing.JTextField txf_Arma5Personaje1;
    public javax.swing.JTextField txf_Arma5Personaje2;
    public javax.swing.JTextField txf_Arma5Personaje3;
    public javax.swing.JTextField txf_Arma5Personaje4;
    public javax.swing.JTextField txf_DireccionApariencia1;
    public javax.swing.JTextField txf_DireccionApariencia2;
    public javax.swing.JTextField txf_DireccionApariencia3;
    public javax.swing.JTextField txf_DireccionApariencia4;
    public javax.swing.JTextField txf_Nombre1;
    public javax.swing.JTextField txf_Nombre2;
    public javax.swing.JTextField txf_Nombre3;
    public javax.swing.JTextField txf_Nombre4;
    // End of variables declaration//GEN-END:variables
}
